package com.dao;
// Generated Oct 8, 2018 6:36:55 PM by Hibernate Tools 4.3.1



/**
 * Joke generated by hbm2java
 */
public class Joke  implements java.io.Serializable {


     private int id;
     private Person person;
     private String content;

    public Joke() {
    }

	
    public Joke(int id, Person person) {
        this.id = id;
        this.person = person;
    }
    public Joke(int id, Person person, String content) {
       this.id = id;
       this.person = person;
       this.content = content;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


